# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fcClientgui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(324, 561)
        self.tabWidget = QtWidgets.QTabWidget(Form1)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 331, 261))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.PictureControls = QtWidgets.QFrame(self.tab_setup)
        self.PictureControls.setGeometry(QtCore.QRect(20, 10, 291, 91))
        self.PictureControls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PictureControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PictureControls.setObjectName("PictureControls")
        self.lightCheckbox = QtWidgets.QCheckBox(self.PictureControls)
        self.lightCheckbox.setGeometry(QtCore.QRect(180, 0, 61, 22))
        self.lightCheckbox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lightCheckbox.setObjectName("lightCheckbox")
        self.prevCheckBox = QtWidgets.QCheckBox(self.PictureControls)
        self.prevCheckBox.setGeometry(QtCore.QRect(180, 20, 81, 22))
        self.prevCheckBox.setObjectName("prevCheckBox")
        self.zoomDial = QtWidgets.QDial(self.PictureControls)
        self.zoomDial.setGeometry(QtCore.QRect(-1, 0, 91, 81))
        self.zoomDial.setMinimum(400)
        self.zoomDial.setMaximum(1000)
        self.zoomDial.setProperty("value", 1000)
        self.zoomDial.setNotchTarget(25.0)
        self.zoomDial.setNotchesVisible(True)
        self.zoomDial.setObjectName("zoomDial")
        self.label_6 = QtWidgets.QLabel(self.PictureControls)
        self.label_6.setGeometry(QtCore.QRect(10, 74, 71, 17))
        self.label_6.setObjectName("label_6")
        self.reverseButton = QtWidgets.QPushButton(self.PictureControls)
        self.reverseButton.setGeometry(QtCore.QRect(120, 60, 31, 27))
        self.reverseButton.setObjectName("reverseButton")
        self.stopButton = QtWidgets.QPushButton(self.PictureControls)
        self.stopButton.setGeometry(QtCore.QRect(160, 60, 41, 27))
        self.stopButton.setObjectName("stopButton")
        self.forwardButton = QtWidgets.QPushButton(self.PictureControls)
        self.forwardButton.setGeometry(QtCore.QRect(210, 60, 31, 27))
        self.forwardButton.setObjectName("forwardButton")
        self.ffdButton = QtWidgets.QPushButton(self.PictureControls)
        self.ffdButton.setGeometry(QtCore.QRect(240, 60, 31, 27))
        self.ffdButton.setObjectName("ffdButton")
        self.fRevButton = QtWidgets.QPushButton(self.PictureControls)
        self.fRevButton.setGeometry(QtCore.QRect(90, 60, 31, 27))
        self.fRevButton.setObjectName("fRevButton")
        self.autoExpCheckBox = QtWidgets.QCheckBox(self.PictureControls)
        self.autoExpCheckBox.setGeometry(QtCore.QRect(180, 40, 91, 22))
        self.autoExpCheckBox.setChecked(True)
        self.autoExpCheckBox.setObjectName("autoExpCheckBox")
        self.lightCheckbox.raise_()
        self.prevCheckBox.raise_()
        self.label_6.raise_()
        self.zoomDial.raise_()
        self.reverseButton.raise_()
        self.stopButton.raise_()
        self.forwardButton.raise_()
        self.ffdButton.raise_()
        self.fRevButton.raise_()
        self.autoExpCheckBox.raise_()
        self.ConfigControls = QtWidgets.QFrame(self.tab_setup)
        self.ConfigControls.setGeometry(QtCore.QRect(20, 120, 291, 71))
        self.ConfigControls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ConfigControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ConfigControls.setObjectName("ConfigControls")
        self.loadConfigButton = QtWidgets.QPushButton(self.ConfigControls)
        self.loadConfigButton.setGeometry(QtCore.QRect(87, 6, 61, 27))
        self.loadConfigButton.setObjectName("loadConfigButton")
        self.saveConfigButton = QtWidgets.QPushButton(self.ConfigControls)
        self.saveConfigButton.setGeometry(QtCore.QRect(152, 5, 41, 27))
        self.saveConfigButton.setObjectName("saveConfigButton")
        self.configFile = QtWidgets.QLineEdit(self.ConfigControls)
        self.configFile.setGeometry(QtCore.QRect(5, 35, 271, 27))
        self.configFile.setObjectName("configFile")
        self.saveConfigButton_2 = QtWidgets.QPushButton(self.ConfigControls)
        self.saveConfigButton_2.setGeometry(QtCore.QRect(200, 5, 81, 27))
        self.saveConfigButton_2.setObjectName("saveConfigButton_2")
        self.label_18 = QtWidgets.QLabel(self.ConfigControls)
        self.label_18.setGeometry(QtCore.QRect(9, 11, 71, 20))
        self.label_18.setObjectName("label_18")
        self.xScroll = QtWidgets.QScrollBar(self.tab_setup)
        self.xScroll.setGeometry(QtCore.QRect(2, 204, 311, 20))
        self.xScroll.setMinimum(200)
        self.xScroll.setMaximum(800)
        self.xScroll.setProperty("value", 500)
        self.xScroll.setOrientation(QtCore.Qt.Horizontal)
        self.xScroll.setObjectName("xScroll")
        self.yScroll = QtWidgets.QScrollBar(self.tab_setup)
        self.yScroll.setGeometry(QtCore.QRect(0, 0, 16, 191))
        self.yScroll.setMinimum(200)
        self.yScroll.setMaximum(800)
        self.yScroll.setProperty("value", 500)
        self.yScroll.setOrientation(QtCore.Qt.Vertical)
        self.yScroll.setInvertedControls(False)
        self.yScroll.setObjectName("yScroll")
        self.tabWidget.addTab(self.tab_setup, "")
        self.tab_cap = QtWidgets.QWidget()
        self.tab_cap.setObjectName("tab_cap")
        self.captureStartBtn = QtWidgets.QPushButton(self.tab_cap)
        self.captureStartBtn.setGeometry(QtCore.QRect(120, 160, 81, 27))
        self.captureStartBtn.setObjectName("captureStartBtn")
        self.captureStopBtn = QtWidgets.QPushButton(self.tab_cap)
        self.captureStopBtn.setGeometry(QtCore.QRect(130, 200, 71, 27))
        self.captureStopBtn.setObjectName("captureStopBtn")
        self.startFrameBox = QtWidgets.QSpinBox(self.tab_cap)
        self.startFrameBox.setGeometry(QtCore.QRect(55, 4, 71, 21))
        self.startFrameBox.setMaximum(20000)
        self.startFrameBox.setProperty("value", 1)
        self.startFrameBox.setObjectName("startFrameBox")
        self.endFrameBox = QtWidgets.QSpinBox(self.tab_cap)
        self.endFrameBox.setGeometry(QtCore.QRect(53, 26, 71, 21))
        self.endFrameBox.setMaximum(20000)
        self.endFrameBox.setSingleStep(100)
        self.endFrameBox.setProperty("value", 3600)
        self.endFrameBox.setObjectName("endFrameBox")
        self.label_2 = QtWidgets.QLabel(self.tab_cap)
        self.label_2.setGeometry(QtCore.QRect(1, 6, 61, 20))
        self.label_2.setObjectName("label_2")
        self.stopsBox = QtWidgets.QDoubleSpinBox(self.tab_cap)
        self.stopsBox.setGeometry(QtCore.QRect(140, 25, 51, 21))
        self.stopsBox.setDecimals(1)
        self.stopsBox.setMinimum(0.5)
        self.stopsBox.setMaximum(5.0)
        self.stopsBox.setSingleStep(0.5)
        self.stopsBox.setProperty("value", 1.0)
        self.stopsBox.setObjectName("stopsBox")
        self.frameLcd = QtWidgets.QLCDNumber(self.tab_cap)
        self.frameLcd.setGeometry(QtCore.QRect(211, 194, 101, 31))
        self.frameLcd.setLineWidth(2)
        self.frameLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.frameLcd.setObjectName("frameLcd")
        self.chooseFolderBtn = QtWidgets.QPushButton(self.tab_cap)
        self.chooseFolderBtn.setGeometry(QtCore.QRect(260, 50, 51, 27))
        self.chooseFolderBtn.setObjectName("chooseFolderBtn")
        self.capFolder = QtWidgets.QLineEdit(self.tab_cap)
        self.capFolder.setGeometry(QtCore.QRect(0, 50, 251, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.capFolder.setFont(font)
        self.capFolder.setText("")
        self.capFolder.setObjectName("capFolder")
        self.label_3 = QtWidgets.QLabel(self.tab_cap)
        self.label_3.setGeometry(QtCore.QRect(1, 29, 51, 16))
        self.label_3.setObjectName("label_3")
        self.captureTestBtn = QtWidgets.QPushButton(self.tab_cap)
        self.captureTestBtn.setGeometry(QtCore.QRect(180, 90, 41, 27))
        self.captureTestBtn.setObjectName("captureTestBtn")
        self.setExposureBtn = QtWidgets.QPushButton(self.tab_cap)
        self.setExposureBtn.setGeometry(QtCore.QRect(10, 90, 171, 27))
        self.setExposureBtn.setObjectName("setExposureBtn")
        self.exposureBox = QtWidgets.QSpinBox(self.tab_cap)
        self.exposureBox.setGeometry(QtCore.QRect(30, 160, 71, 21))
        self.exposureBox.setFrame(True)
        self.exposureBox.setReadOnly(True)
        self.exposureBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.exposureBox.setMaximum(1000000)
        self.exposureBox.setObjectName("exposureBox")
        self.exposureUpBtn = QtWidgets.QPushButton(self.tab_cap)
        self.exposureUpBtn.setGeometry(QtCore.QRect(260, 90, 41, 21))
        self.exposureUpBtn.setObjectName("exposureUpBtn")
        self.exposureDownBtn = QtWidgets.QPushButton(self.tab_cap)
        self.exposureDownBtn.setGeometry(QtCore.QRect(220, 90, 41, 21))
        self.exposureDownBtn.setObjectName("exposureDownBtn")
        self.bracketing = QtWidgets.QSpinBox(self.tab_cap)
        self.bracketing.setGeometry(QtCore.QRect(150, 3, 41, 21))
        self.bracketing.setMinimum(1)
        self.bracketing.setMaximum(5)
        self.bracketing.setObjectName("bracketing")
        self.label_20 = QtWidgets.QLabel(self.tab_cap)
        self.label_20.setGeometry(QtCore.QRect(191, 4, 101, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_cap)
        self.label_21.setGeometry(QtCore.QRect(191, 26, 41, 21))
        self.label_21.setObjectName("label_21")
        self.captureFrmRev = QtWidgets.QPushButton(self.tab_cap)
        self.captureFrmRev.setGeometry(QtCore.QRect(170, 130, 51, 27))
        self.captureFrmRev.setObjectName("captureFrmRev")
        self.captureFrmAdv = QtWidgets.QPushButton(self.tab_cap)
        self.captureFrmAdv.setGeometry(QtCore.QRect(220, 130, 51, 27))
        self.captureFrmAdv.setObjectName("captureFrmAdv")
        self.label_11 = QtWidgets.QLabel(self.tab_cap)
        self.label_11.setGeometry(QtCore.QRect(0, 120, 121, 17))
        self.label_11.setObjectName("label_11")
        self.exposureBoxMin = QtWidgets.QSpinBox(self.tab_cap)
        self.exposureBoxMin.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.exposureBoxMin.setFrame(True)
        self.exposureBoxMin.setReadOnly(True)
        self.exposureBoxMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.exposureBoxMin.setMaximum(1000000)
        self.exposureBoxMin.setObjectName("exposureBoxMin")
        self.exposureBoxMax = QtWidgets.QSpinBox(self.tab_cap)
        self.exposureBoxMax.setGeometry(QtCore.QRect(30, 180, 71, 21))
        self.exposureBoxMax.setFrame(True)
        self.exposureBoxMax.setReadOnly(True)
        self.exposureBoxMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.exposureBoxMax.setMaximum(1000000)
        self.exposureBoxMax.setObjectName("exposureBoxMax")
        self.label_13 = QtWidgets.QLabel(self.tab_cap)
        self.label_13.setGeometry(QtCore.QRect(2, 206, 71, 17))
        self.label_13.setObjectName("label_13")
        self.gainBoxA = QtWidgets.QSpinBox(self.tab_cap)
        self.gainBoxA.setGeometry(QtCore.QRect(40, 204, 41, 21))
        self.gainBoxA.setFrame(True)
        self.gainBoxA.setReadOnly(True)
        self.gainBoxA.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gainBoxA.setMaximum(1000000)
        self.gainBoxA.setObjectName("gainBoxA")
        self.gainBoxD = QtWidgets.QSpinBox(self.tab_cap)
        self.gainBoxD.setGeometry(QtCore.QRect(80, 204, 41, 21))
        self.gainBoxD.setFrame(True)
        self.gainBoxD.setReadOnly(True)
        self.gainBoxD.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gainBoxD.setMaximum(1000000)
        self.gainBoxD.setObjectName("gainBoxD")
        self.label_24 = QtWidgets.QLabel(self.tab_cap)
        self.label_24.setGeometry(QtCore.QRect(0, 140, 31, 17))
        self.label_24.setObjectName("label_24")
        self.label_33 = QtWidgets.QLabel(self.tab_cap)
        self.label_33.setGeometry(QtCore.QRect(0, 160, 31, 17))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_cap)
        self.label_34.setGeometry(QtCore.QRect(0, 180, 31, 17))
        self.label_34.setObjectName("label_34")
        self.captureFrmRev_2 = QtWidgets.QPushButton(self.tab_cap)
        self.captureFrmRev_2.setGeometry(QtCore.QRect(120, 130, 51, 27))
        self.captureFrmRev_2.setObjectName("captureFrmRev_2")
        self.captureFrmAdv_2 = QtWidgets.QPushButton(self.tab_cap)
        self.captureFrmAdv_2.setGeometry(QtCore.QRect(270, 130, 51, 27))
        self.captureFrmAdv_2.setObjectName("captureFrmAdv_2")
        self.pauseBox = QtWidgets.QCheckBox(self.tab_cap)
        self.pauseBox.setGeometry(QtCore.QRect(215, 162, 99, 22))
        self.pauseBox.setObjectName("pauseBox")
        self.tabWidget.addTab(self.tab_cap, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.vflip = QtWidgets.QCheckBox(self.tab)
        self.vflip.setGeometry(QtCore.QRect(0, 0, 61, 22))
        self.vflip.setObjectName("vflip")
        self.hflip = QtWidgets.QCheckBox(self.tab)
        self.hflip.setGeometry(QtCore.QRect(70, 0, 97, 22))
        self.hflip.setObjectName("hflip")
        self.bw = QtWidgets.QCheckBox(self.tab)
        self.bw.setGeometry(QtCore.QRect(140, 0, 51, 22))
        self.bw.setObjectName("bw")
        self.drcBox = QtWidgets.QComboBox(self.tab)
        self.drcBox.setGeometry(QtCore.QRect(50, 30, 78, 27))
        self.drcBox.setObjectName("drcBox")
        self.drcBox.addItem("")
        self.drcBox.setItemText(0, "off")
        self.drcBox.addItem("")
        self.drcBox.setItemText(1, "low")
        self.drcBox.addItem("")
        self.drcBox.setItemText(2, "medium")
        self.drcBox.addItem("")
        self.drcBox.setItemText(3, "high")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.label_4.setObjectName("label_4")
        self.sharpnessBox = QtWidgets.QSpinBox(self.tab)
        self.sharpnessBox.setGeometry(QtCore.QRect(210, 30, 60, 27))
        self.sharpnessBox.setMinimum(-100)
        self.sharpnessBox.setMaximum(100)
        self.sharpnessBox.setProperty("value", -100)
        self.sharpnessBox.setObjectName("sharpnessBox")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(140, 33, 71, 20))
        self.label_16.setObjectName("label_16")
        self.stillCap = QtWidgets.QCheckBox(self.tab)
        self.stillCap.setGeometry(QtCore.QRect(0, 60, 191, 22))
        self.stillCap.setObjectName("stillCap")
        self.saveinits = QtWidgets.QPushButton(self.tab)
        self.saveinits.setGeometry(QtCore.QRect(30, 190, 231, 27))
        self.saveinits.setObjectName("saveinits")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(7, 85, 141, 17))
        self.label.setObjectName("label")
        self.resolution = QtWidgets.QComboBox(self.tab)
        self.resolution.setGeometry(QtCore.QRect(160, 80, 121, 27))
        self.resolution.setObjectName("resolution")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.resolution.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.Post = QtWidgets.QWidget()
        self.Post.setObjectName("Post")
        self.label_37 = QtWidgets.QLabel(self.Post)
        self.label_37.setGeometry(QtCore.QRect(5, 0, 310, 17))
        self.label_37.setObjectName("label_37")
        self.lensCorrection = QtWidgets.QCheckBox(self.Post)
        self.lensCorrection.setGeometry(QtCore.QRect(0, 80, 131, 22))
        self.lensCorrection.setObjectName("lensCorrection")
        self.cropping = QtWidgets.QCheckBox(self.Post)
        self.cropping.setGeometry(QtCore.QRect(0, 170, 61, 22))
        self.cropping.setObjectName("cropping")
        self.rotation = QtWidgets.QCheckBox(self.Post)
        self.rotation.setGeometry(QtCore.QRect(0, 140, 81, 22))
        self.rotation.setObjectName("rotation")
        self.rotationBox = QtWidgets.QDoubleSpinBox(self.Post)
        self.rotationBox.setGeometry(QtCore.QRect(80, 140, 69, 27))
        self.rotationBox.setMinimum(-100.0)
        self.rotationBox.setMaximum(100.0)
        self.rotationBox.setObjectName("rotationBox")
        self.cropTop = QtWidgets.QSpinBox(self.Post)
        self.cropTop.setGeometry(QtCore.QRect(97, 170, 61, 27))
        self.cropTop.setMaximum(999)
        self.cropTop.setObjectName("cropTop")
        self.cropBottom = QtWidgets.QSpinBox(self.Post)
        self.cropBottom.setGeometry(QtCore.QRect(97, 200, 61, 27))
        self.cropBottom.setMaximum(999)
        self.cropBottom.setObjectName("cropBottom")
        self.cropLeft = QtWidgets.QSpinBox(self.Post)
        self.cropLeft.setGeometry(QtCore.QRect(20, 199, 61, 27))
        self.cropLeft.setMaximum(999)
        self.cropLeft.setObjectName("cropLeft")
        self.cropRight = QtWidgets.QSpinBox(self.Post)
        self.cropRight.setGeometry(QtCore.QRect(173, 200, 61, 27))
        self.cropRight.setMaximum(999)
        self.cropRight.setObjectName("cropRight")
        self.label_38 = QtWidgets.QLabel(self.Post)
        self.label_38.setGeometry(QtCore.QRect(10, 204, 16, 17))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Post)
        self.label_39.setGeometry(QtCore.QRect(160, 205, 16, 17))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.Post)
        self.label_40.setGeometry(QtCore.QRect(86, 205, 16, 17))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.Post)
        self.label_41.setGeometry(QtCore.QRect(86, 175, 16, 17))
        self.label_41.setObjectName("label_41")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.Post)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(140, 80, 121, 27))
        self.doubleSpinBox_2.setDecimals(6)
        self.doubleSpinBox_2.setMinimum(-99.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.lensXctrAdjust = QtWidgets.QDoubleSpinBox(self.Post)
        self.lensXctrAdjust.setGeometry(QtCore.QRect(110, 110, 69, 27))
        self.lensXctrAdjust.setMinimum(-50.0)
        self.lensXctrAdjust.setMaximum(50.0)
        self.lensXctrAdjust.setObjectName("lensXctrAdjust")
        self.lensYctrAdjust = QtWidgets.QDoubleSpinBox(self.Post)
        self.lensYctrAdjust.setGeometry(QtCore.QRect(230, 110, 69, 27))
        self.lensYctrAdjust.setMinimum(-50.0)
        self.lensYctrAdjust.setMaximum(50.0)
        self.lensYctrAdjust.setObjectName("lensYctrAdjust")
        self.label_42 = QtWidgets.QLabel(self.Post)
        self.label_42.setGeometry(QtCore.QRect(214, 115, 16, 17))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.Post)
        self.label_43.setGeometry(QtCore.QRect(5, 114, 101, 17))
        self.label_43.setObjectName("label_43")
        self.antiVignetting = QtWidgets.QCheckBox(self.Post)
        self.antiVignetting.setGeometry(QtCore.QRect(0, 30, 131, 22))
        self.antiVignetting.setObjectName("antiVignetting")
        self.getBlank = QtWidgets.QPushButton(self.Post)
        self.getBlank.setGeometry(QtCore.QRect(140, 30, 131, 30))
        self.getBlank.setObjectName("getBlank")
        self.tabWidget.addTab(self.Post, "")
        self.groupBox_2 = QtWidgets.QGroupBox(Form1)
        self.groupBox_2.setGeometry(QtCore.QRect(4, 389, 311, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.blueGain = QtWidgets.QSlider(self.groupBox_2)
        self.blueGain.setEnabled(False)
        self.blueGain.setGeometry(QtCore.QRect(30, 30, 160, 29))
        self.blueGain.setMinimum(50)
        self.blueGain.setMaximum(400)
        self.blueGain.setProperty("value", 200)
        self.blueGain.setOrientation(QtCore.Qt.Horizontal)
        self.blueGain.setObjectName("blueGain")
        self.redGain = QtWidgets.QSlider(self.groupBox_2)
        self.redGain.setEnabled(False)
        self.redGain.setGeometry(QtCore.QRect(30, 60, 160, 29))
        self.redGain.setMinimum(50)
        self.redGain.setMaximum(250)
        self.redGain.setSingleStep(1)
        self.redGain.setPageStep(10)
        self.redGain.setProperty("value", 100)
        self.redGain.setSliderPosition(100)
        self.redGain.setOrientation(QtCore.Qt.Horizontal)
        self.redGain.setObjectName("redGain")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(0, 63, 31, 20))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(0, 33, 31, 20))
        self.label_8.setObjectName("label_8")
        self.blueGainBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.blueGainBox.setEnabled(False)
        self.blueGainBox.setGeometry(QtCore.QRect(190, 30, 60, 27))
        self.blueGainBox.setMinimum(50)
        self.blueGainBox.setMaximum(400)
        self.blueGainBox.setProperty("value", 200)
        self.blueGainBox.setObjectName("blueGainBox")
        self.redGainBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.redGainBox.setEnabled(False)
        self.redGainBox.setGeometry(QtCore.QRect(190, 60, 60, 27))
        self.redGainBox.setMinimum(50)
        self.redGainBox.setMaximum(250)
        self.redGainBox.setProperty("value", 100)
        self.redGainBox.setObjectName("redGainBox")
        self.saturation = QtWidgets.QSlider(self.groupBox_2)
        self.saturation.setGeometry(QtCore.QRect(57, 90, 131, 29))
        self.saturation.setMinimum(-100)
        self.saturation.setMaximum(100)
        self.saturation.setProperty("value", 0)
        self.saturation.setSliderPosition(0)
        self.saturation.setOrientation(QtCore.Qt.Horizontal)
        self.saturation.setObjectName("saturation")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(0, 93, 31, 20))
        self.label_10.setObjectName("label_10")
        self.saturationBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.saturationBox.setGeometry(QtCore.QRect(190, 90, 60, 27))
        self.saturationBox.setMinimum(-100)
        self.saturationBox.setMaximum(100)
        self.saturationBox.setObjectName("saturationBox")
        self.blueResetBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.blueResetBtn.setEnabled(False)
        self.blueResetBtn.setGeometry(QtCore.QRect(250, 30, 51, 27))
        self.blueResetBtn.setObjectName("blueResetBtn")
        self.redResetBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.redResetBtn.setEnabled(False)
        self.redResetBtn.setGeometry(QtCore.QRect(250, 60, 51, 27))
        self.redResetBtn.setObjectName("redResetBtn")
        self.resetSaturationBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.resetSaturationBtn.setGeometry(QtCore.QRect(250, 90, 51, 27))
        self.resetSaturationBtn.setObjectName("resetSaturationBtn")
        self.colorSetBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.colorSetBtn.setGeometry(QtCore.QRect(230, 0, 71, 24))
        self.colorSetBtn.setObjectName("colorSetBtn")
        self.awbBox = QtWidgets.QComboBox(self.groupBox_2)
        self.awbBox.setGeometry(QtCore.QRect(110, 0, 121, 24))
        self.awbBox.setObjectName("awbBox")
        self.awbBox.addItem("")
        self.awbBox.setItemText(0, "off")
        self.awbBox.addItem("")
        self.awbBox.setItemText(1, "auto")
        self.awbBox.addItem("")
        self.awbBox.setItemText(2, "sunlight")
        self.awbBox.addItem("")
        self.awbBox.setItemText(3, "cloudy")
        self.awbBox.addItem("")
        self.awbBox.addItem("")
        self.awbBox.addItem("")
        self.awbBox.addItem("")
        self.awbBox.addItem("")
        self.awbBox.addItem("")
        self.resetContBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.resetContBtn.setGeometry(QtCore.QRect(250, 120, 51, 27))
        self.resetContBtn.setObjectName("resetContBtn")
        self.contrast = QtWidgets.QSlider(self.groupBox_2)
        self.contrast.setGeometry(QtCore.QRect(57, 120, 131, 29))
        self.contrast.setMinimum(-100)
        self.contrast.setMaximum(100)
        self.contrast.setProperty("value", 0)
        self.contrast.setSliderPosition(0)
        self.contrast.setOrientation(QtCore.Qt.Horizontal)
        self.contrast.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.contrast.setTickInterval(10)
        self.contrast.setObjectName("contrast")
        self.contrastBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.contrastBox.setGeometry(QtCore.QRect(190, 120, 60, 27))
        self.contrastBox.setMinimum(-100)
        self.contrastBox.setMaximum(100)
        self.contrastBox.setProperty("value", 0)
        self.contrastBox.setObjectName("contrastBox")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(-1, 122, 31, 20))
        self.label_17.setObjectName("label_17")
        self.groupBox_3 = QtWidgets.QGroupBox(Form1)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 304, 321, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(4, 22, 31, 16))
        self.label_15.setObjectName("label_15")
        self.brightness = QtWidgets.QSlider(self.groupBox_3)
        self.brightness.setGeometry(QtCore.QRect(29, 20, 151, 29))
        self.brightness.setMinimum(0)
        self.brightness.setMaximum(100)
        self.brightness.setProperty("value", 50)
        self.brightness.setSliderPosition(50)
        self.brightness.setOrientation(QtCore.Qt.Horizontal)
        self.brightness.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.brightness.setTickInterval(10)
        self.brightness.setObjectName("brightness")
        self.brightnessBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.brightnessBox.setGeometry(QtCore.QRect(190, 20, 60, 27))
        self.brightnessBox.setMaximum(100)
        self.brightnessBox.setProperty("value", 50)
        self.brightnessBox.setObjectName("brightnessBox")
        self.resetBrightBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.resetBrightBtn.setGeometry(QtCore.QRect(250, 20, 51, 27))
        self.resetBrightBtn.setObjectName("resetBrightBtn")
        self.EV = QtWidgets.QSpinBox(self.groupBox_3)
        self.EV.setGeometry(QtCore.QRect(180, 56, 60, 21))
        self.EV.setMinimum(-25)
        self.EV.setMaximum(25)
        self.EV.setProperty("value", 0)
        self.EV.setObjectName("EV")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(0, 60, 171, 16))
        self.label_22.setObjectName("label_22")
        self.statusBar = QtWidgets.QLabel(Form1)
        self.statusBar.setGeometry(QtCore.QRect(0, 540, 321, 17))
        self.statusBar.setObjectName("statusBar")

        self.retranslateUi(Form1)
        self.tabWidget.setCurrentIndex(0)
        self.awbBox.setCurrentIndex(1)
        self.blueGain.valueChanged['int'].connect(Form1.setGainBlue)
        self.redGain.valueChanged['int'].connect(Form1.setGainRed)
        self.redGain.valueChanged['int'].connect(self.redGainBox.setValue)
        self.blueGain.valueChanged['int'].connect(self.blueGainBox.setValue)
        self.redGainBox.valueChanged['int'].connect(self.redGain.setValue)
        self.blueGainBox.valueChanged['int'].connect(self.blueGain.setValue)
        self.blueGainBox.valueChanged['int'].connect(Form1.setGainBlue)
        self.redGainBox.valueChanged['int'].connect(Form1.setGainRed)
        self.brightness.valueChanged['int'].connect(self.brightnessBox.setValue)
        self.brightnessBox.valueChanged['int'].connect(self.brightness.setValue)
        self.brightnessBox.valueChanged['int'].connect(Form1.setBright)
        self.saturationBox.valueChanged['int'].connect(Form1.setSaturation)
        self.saturationBox.valueChanged['int'].connect(self.saturation.setValue)
        self.saturation.valueChanged['int'].connect(self.saturationBox.setValue)
        self.resetBrightBtn.clicked.connect(Form1.resetBright)
        self.resetContBtn.clicked.connect(Form1.resetContrast)
        self.blueResetBtn.clicked.connect(Form1.resetGainBlue)
        self.redResetBtn.clicked.connect(Form1.resetGainRed)
        self.resetSaturationBtn.clicked.connect(Form1.resetSaturation)
        self.contrast.valueChanged['int'].connect(self.contrastBox.setValue)
        self.contrastBox.valueChanged['int'].connect(self.contrast.setValue)
        self.contrastBox.valueChanged['int'].connect(Form1.setContrast)
        self.colorSetBtn.clicked.connect(Form1.colorSet)
        self.awbBox.currentIndexChanged['QString'].connect(Form1.setAWBmode)
        self.EV.valueChanged['int'].connect(Form1.setEV)
        self.sharpnessBox.valueChanged['int'].connect(Form1.setSharpness)
        self.captureFrmRev.clicked.connect(Form1.capFrameRev)
        self.fRevButton.clicked.connect(Form1.motorfrev)
        self.ffdButton.clicked.connect(Form1.motorffd)
        self.captureStartBtn.clicked.connect(Form1.captureStart)
        self.vflip.toggled['bool'].connect(Form1.setVFlip)
        self.cropping.clicked['bool'].connect(Form1.setCrop)
        self.cropTop.valueChanged['int'].connect(Form1.setCropT)
        self.lightCheckbox.clicked['bool'].connect(Form1.lightSet)
        self.stopButton.clicked.connect(Form1.motorStop)
        self.hflip.toggled['bool'].connect(Form1.setHFlip)
        self.tabWidget.currentChanged['int'].connect(Form1.tabChanged)
        self.reverseButton.clicked.connect(Form1.motorRev)
        self.forwardButton.clicked.connect(Form1.motorFwd)
        self.captureStopBtn.clicked.connect(Form1.captureEnd)
        self.chooseFolderBtn.clicked.connect(Form1.chooseFolder)
        self.endFrameBox.valueChanged['int'].connect(Form1.setEndFrame)
        self.bw.clicked['bool'].connect(self.blueGain.setDisabled)
        self.bw.clicked['bool'].connect(self.redGain.setDisabled)
        self.startFrameBox.valueChanged['int'].connect(Form1.setStartFrame)
        self.drcBox.currentIndexChanged['QString'].connect(Form1.setDrc)
        self.prevCheckBox.clicked['bool'].connect(Form1.previewSet)
        self.loadConfigButton.clicked.connect(Form1.loadConfig)
        self.stopsBox.valueChanged['double'].connect(Form1.setBlendStops)
        self.bw.toggled['bool'].connect(Form1.setBW)
        self.captureTestBtn.clicked.connect(Form1.takeTestPhoto)
        self.exposureUpBtn.clicked.connect(Form1.setExposureUp)
        self.setExposureBtn.clicked.connect(Form1.setExposure)
        self.saveConfigButton.clicked.connect(Form1.saveCurrentConfig)
        self.saveConfigButton_2.clicked.connect(Form1.saveConfig)
        self.yScroll.valueChanged['int'].connect(Form1.setY)
        self.xScroll.valueChanged['int'].connect(Form1.setX)
        self.exposureDownBtn.clicked.connect(Form1.setExposureDown)
        self.stillCap.clicked['bool'].connect(Form1.setStillPort)
        self.bracketing.valueChanged['int'].connect(Form1.setBlend)
        self.zoomDial.valueChanged['int'].connect(Form1.setZoom)
        self.captureFrmAdv.clicked.connect(Form1.capFrameAdv)
        self.captureFrmRev_2.clicked.connect(Form1.capFrameRev10)
        self.captureFrmAdv_2.clicked.connect(Form1.capFrameAdv10)
        self.autoExpCheckBox.toggled['bool'].connect(Form1.setAutoExp)
        self.pauseBox.toggled['bool'].connect(Form1.capturePause)
        self.resolution.currentIndexChanged['int'].connect(Form1.setCapRes)
        self.rotation.clicked['bool'].connect(Form1.setRotation)
        self.lensCorrection.clicked['bool'].connect(Form1.setLensCorr)
        self.doubleSpinBox_2.valueChanged['double'].connect(Form1.setLensCorrValue)
        self.lensXctrAdjust.valueChanged['double'].connect(Form1.setLensCorrX)
        self.lensYctrAdjust.valueChanged['double'].connect(Form1.setLensCorrY)
        self.cropLeft.valueChanged['int'].connect(Form1.setCropL)
        self.rotationBox.valueChanged['double'].connect(Form1.setRotationValue)
        self.cropRight.valueChanged['int'].connect(Form1.setCropR)
        self.cropBottom.valueChanged['int'].connect(Form1.setCropB)
        self.getBlank.clicked.connect(Form1.getBlankImage)
        self.antiVignetting.clicked['bool'].connect(Form1.setVignetting)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Pi Film Capture"))
        self.PictureControls.setToolTip(_translate("Form1", "<html><head/><body><p>If checked, camera will automatically adjust exposure. Should normally be on, but is turned OFF when switching back from capture mode, so camera can be adjusted without affecting capture shutter speed or exposure gains.</p></body></html>"))
        self.lightCheckbox.setText(_translate("Form1", "Light"))
        self.prevCheckBox.setText(_translate("Form1", "Preview"))
        self.label_6.setText(_translate("Form1", "0.4        1.0"))
        self.reverseButton.setText(_translate("Form1", "<-"))
        self.stopButton.setText(_translate("Form1", "Stop"))
        self.forwardButton.setText(_translate("Form1", "->"))
        self.ffdButton.setText(_translate("Form1", ">>"))
        self.fRevButton.setText(_translate("Form1", "<<"))
        self.autoExpCheckBox.setToolTip(_translate("Form1", "Automatically adjusts exposure.  On by default, but turned off when switching back from capture, so frame can be adjusted without affecting shutter speed or gains."))
        self.autoExpCheckBox.setText(_translate("Form1", "Auto Exp"))
        self.loadConfigButton.setText(_translate("Form1", "Load..."))
        self.saveConfigButton.setText(_translate("Form1", "Save"))
        self.saveConfigButton_2.setText(_translate("Form1", "Save As..."))
        self.label_18.setText(_translate("Form1", "Config File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("Form1", "Setup"))
        self.captureStartBtn.setText(_translate("Form1", "Start"))
        self.captureStopBtn.setToolTip(_translate("Form1", "Stop Capturing"))
        self.captureStopBtn.setText(_translate("Form1", "Stop"))
        self.label_2.setText(_translate("Form1", "Start on"))
        self.chooseFolderBtn.setText(_translate("Form1", "Folder"))
        self.capFolder.setPlaceholderText(_translate("Form1", "Choose Capture Folder"))
        self.label_3.setText(_translate("Form1", "Frames"))
        self.captureTestBtn.setText(_translate("Form1", "Test "))
        self.setExposureBtn.setText(_translate("Form1", "Auto-set/Test Exposure"))
        self.exposureBox.setToolTip(_translate("Form1", "Minimum shutter speed asked for by the camera"))
        self.exposureUpBtn.setText(_translate("Form1", "+1/3"))
        self.exposureDownBtn.setText(_translate("Form1", "-1/3"))
        self.label_20.setText(_translate("Form1", "Shots/Frame"))
        self.label_21.setText(_translate("Form1", "Stops"))
        self.captureFrmRev.setToolTip(_translate("Form1", "Rewind One Frame"))
        self.captureFrmRev.setText(_translate("Form1", "<- 1"))
        self.captureFrmAdv.setToolTip(_translate("Form1", "Advance One Frame"))
        self.captureFrmAdv.setText(_translate("Form1", "1 ->"))
        self.label_11.setText(_translate("Form1", "Shutter (max66k)"))
        self.exposureBoxMin.setToolTip(_translate("Form1", "<html><head/><body><p>The \'average\' exposure speed as reported by the camera.  Bracketed exposures will be calculated by adjusting this value. Can be manually adjusted using \'+/-\' buttons above. </p></body></html>"))
        self.exposureBoxMax.setToolTip(_translate("Form1", "<html><head/><body><p>Maximum shutter speed needed by camera in microseconds, based on camera\'s current \'mid\' shutter speed and bracketing settings.  IMPORTANT! This is a target only: if the camera\'s framerate cannot support it, the it will not be achieved!  If it\'s too high, try using auto-set to calculate new exposure values, possibly adjusting the gains.</p></body></html>"))
        self.label_13.setText(_translate("Form1", "Gains"))
        self.gainBoxA.setToolTip(_translate("Form1", "Analog Gain reported by camera. Range from 1 to 8.  For low noise should be as near 1 as possible"))
        self.gainBoxD.setToolTip(_translate("Form1", "Digital gain reported by camera, from 1-8.  If not near 1, light is too low"))
        self.label_24.setText(_translate("Form1", "Min"))
        self.label_33.setText(_translate("Form1", "Mid"))
        self.label_34.setText(_translate("Form1", "Max"))
        self.captureFrmRev_2.setToolTip(_translate("Form1", "Rewind One Frame"))
        self.captureFrmRev_2.setText(_translate("Form1", "<-10"))
        self.captureFrmAdv_2.setToolTip(_translate("Form1", "Advance One Frame"))
        self.captureFrmAdv_2.setText(_translate("Form1", "10->"))
        self.pauseBox.setText(_translate("Form1", "Pause"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cap), _translate("Form1", "Capture"))
        self.vflip.setText(_translate("Form1", "vflip"))
        self.hflip.setText(_translate("Form1", "hflip"))
        self.bw.setText(_translate("Form1", "b/w"))
        self.label_4.setText(_translate("Form1", "DRC"))
        self.label_16.setText(_translate("Form1", "Sharpness"))
        self.stillCap.setToolTip(_translate("Form1", "When"))
        self.stillCap.setText(_translate("Form1", "Capture from Stills Port"))
        self.saveinits.setText(_translate("Form1", " Save Current Settings as Startup"))
        self.label.setText(_translate("Form1", "Capture Resolution:"))
        self.resolution.setItemText(0, _translate("Form1", "2592x1944"))
        self.resolution.setItemText(1, _translate("Form1", "1600x1200"))
        self.resolution.setItemText(2, _translate("Form1", "1440x1080"))
        self.resolution.setItemText(3, _translate("Form1", "1296x972"))
        self.resolution.setItemText(4, _translate("Form1", "1024x768"))
        self.resolution.setItemText(5, _translate("Form1", "800x600"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form1", "Advanced"))
        self.label_37.setText(_translate("Form1", "Post-Capture Operations (on Client)"))
        self.lensCorrection.setText(_translate("Form1", "Lens Correction"))
        self.cropping.setText(_translate("Form1", "Crop"))
        self.rotation.setText(_translate("Form1", "Rotate"))
        self.label_38.setText(_translate("Form1", "L"))
        self.label_39.setText(_translate("Form1", "R"))
        self.label_40.setText(_translate("Form1", "B"))
        self.label_41.setText(_translate("Form1", "T"))
        self.label_42.setText(_translate("Form1", "Y"))
        self.label_43.setText(_translate("Form1", "Pct from ctr: X"))
        self.antiVignetting.setText(_translate("Form1", "AntiVignetting"))
        self.getBlank.setText(_translate("Form1", "Get Blank Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Post), _translate("Form1", "PostCap"))
        self.groupBox_2.setTitle(_translate("Form1", "Color"))
        self.label_5.setText(_translate("Form1", "Red"))
        self.label_8.setText(_translate("Form1", "Blue"))
        self.label_10.setText(_translate("Form1", "Sat"))
        self.blueResetBtn.setText(_translate("Form1", "Reset"))
        self.redResetBtn.setText(_translate("Form1", "Reset"))
        self.resetSaturationBtn.setText(_translate("Form1", "Reset"))
        self.colorSetBtn.setToolTip(_translate("Form1", "<html><head/><body><p>When clicked, Blue and Red color gains will be set to those used by the current WB setting, and auto-white balance will be turned off so that the values may be manually adjusted.</p></body></html>"))
        self.colorSetBtn.setText(_translate("Form1", "Use this"))
        self.awbBox.setItemText(4, _translate("Form1", "shade"))
        self.awbBox.setItemText(5, _translate("Form1", "tungsten"))
        self.awbBox.setItemText(6, _translate("Form1", "fluorescent"))
        self.awbBox.setItemText(7, _translate("Form1", "incandescent"))
        self.awbBox.setItemText(8, _translate("Form1", "flash"))
        self.awbBox.setItemText(9, _translate("Form1", "horizon"))
        self.resetContBtn.setText(_translate("Form1", "Reset"))
        self.label_17.setText(_translate("Form1", "Cont"))
        self.groupBox_3.setTitle(_translate("Form1", "Cam Settings"))
        self.label_15.setText(_translate("Form1", "Brt"))
        self.resetBrightBtn.setText(_translate("Form1", "Reset"))
        self.EV.setToolTip(_translate("Form1", "<html><head/><body><p>Changes the effective exposure by 1/6 stop.  This affects previews and the initial setting for capture (plus any smart adjustments).  Changing it during capture will have NO EFFECT unless capture is paused and &quot;Set Exposure&quot; is pressed.</p></body></html>"))
        self.label_22.setText(_translate("Form1", "Exposure Compensation"))
        self.statusBar.setText(_translate("Form1", "Program Started"))

