MOTOR_FWD =     '>'
MOTOR_REV =     '<'
MOTOR_FFD =     '.'
MOTOR_FREV =     ','
MOTOR_STOP =    ' '
CAP_FRAME_ADV = ';'
CAP_FRAME_REV = ':'
LIGHT_OFF =     'L'
LIGHT_ON =      'l'
PREVIEW_ON =    'p'
PREVIEW_OFF =   'P'
AUTOEXP_ON =    '4'
AUTOEXP_OFF =   '$'

SETX =          '8'
SETY =          '7'
SETZ =          '6'
AWB_MODE =      'w'
GAIN_RED =      'r'
GAIN_BLUE =     'b'
BRIGHTNESS =    'y'
EXP_COMP =      'e'
SATURATION =    's'
CONTRAST =      'k'

FIX_GAINS =     'W'
DRC =           'd'
HFLIP_ON =      'h'
HFLIP_OFF =     'H'
VFLIP_ON =      'v'
VFLIP_OFF =     'V'
BW_ON =         'g'
BW_OFF =        'G'
SHARPNESS =     'Z'
VID_PORT_ON =   'J'
VID_PORT_OFF =  'j'


CAPTURE_ON =    'c'
CAPTURE_OFF =   'C'
BRACKETING_SHOTS='f'
BRACKETING_STOPS ='F'
FIX_EXPOSURE =  'x'
SS_SLOWER =     'a'
SS_FASTER =     'A'

QUIT = 'q'
CLIENT_QUIT = '0'
TEST_PHOTO = 't'
START_CAPTURE = 'o'
STOP_CAPTURE = 'O'
SET_MOTOR_SPEED = 'n'
SET_SIZE = '*'
